version: 2

project_name: defi

builds:
  - id: defi
    builder: rust
    dir: rust
    binary: defi
    command: zigbuild
    flags:
      - --release
      - -p=defi-cli
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin
    env:
      - DEFI_CLI_VERSION={{ if .IsSnapshot }}{{ .Version }}-snapshot{{ else }}{{ .Tag }}{{ end }}
      - DEFI_BUILD_COMMIT={{ .ShortCommit }}
      - DEFI_BUILD_DATE={{ .Date }}

archives:
  - id: default
    ids:
      - defi
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-dev"

release:
  prerelease: auto

changelog:
  use: github-native
